### PR TITLE
Ics

### PR DESCRIPTION
**Pull request by Zaladar**
Now every thing is working as it should, will look into fixing the CSS for the calendar download button so that it looks good and figure out a god position for it.

Leaving this in its own branch in case there is some development going on for the master branch.

### CODE REVIEW

**Comment by krakan** [comment]
According to the ICS file for 2022 it's the days before midsummer's eve and all saints eve that are special, not the eve's themselves - so there appears to be an off by one error.

**Comment by Zaladar** [comment]
Had a look at this and i found the issue, will rebuild the expected function within the Calendar file instead with some smaller tweaks.

From what I gather the red days are provided by maconomy, this behavior could be copied but would require a rebuilding of the logic for redday calculation. Thus I think copying the redday calculation from demo within calendar will be more efficient, it will require maintenance when we change red days for init.

Not entirely sure why there is an issue in the demo variant thought, what i can gather the red day is put on the wrong day and it seems to have something to do with the switch case for determining red days in Demo.

**Comment by krakan** [comment]
Yes, I contemplated the maintenance issue when I created the Demo class - but these dates have been stable since at least 1997 so I decided not to worry about it ... :smiley:

**Comment by Zaladar** [comment]
Made the changes to calendar so that it has an internal functions to determine whether the days are supposed to be red days or not.

ICS file will now hold which day is what i.e. if it is newyears eve the holiday name will be in the sumary of the calendar event.
example of a calendar with only new years day is shown in calendar file.

Updated demo to fix it's calculation for midsummer and al saints, it added diff twice.

**Pull request merged**
