### PR TITLE
Restyling and updating the frontend design to be responsive

### PR DESCRIPTION
**Pull request by Bluebottel**
_aiqueneldar knows me and have given thumbs up as well as tested the design along with me._

The time report, login and edit rows pages have all be restyled to resize, notably up, 
gracefully on mobile devices  and been give a bit of a polish with two new themes that attempt to keep the spirit of the old ones. There's a dark and light theme only meaning the newer gray one didn't make the cut however it shouldn't be much work to implement it just by looking at the structure of the other ones.

No functional changes have been made and nothing has been added so the site works exactly the same as before.

**CSS notes**
I've attempted to follow [this](http://getbem.com/naming/) naming schema to make it obvious what the classes are doing and what they should be applied to as well as used custom CSS variables to give hints of a particular values purpose. If I've used a non-obvious method instead of what might appear to be a more straight forward one I've commented on it explaining why.

I've made almost exclusive use of class selectors since those all have the same priority when it comes to styling the element, making it predictable what will take precedence at any point.

**Design notes**
The method I've used to pick the colors of themes is to start with either black or white and then picked a color that should be that themes primary color. From then a handful of similar but sufficiently contrasting colors are chosen to be used whenever the primary color needs a contrasting edge or different background. [This site](https://mycolor.space) is useful.

**Previews**
dark time report
edit dark
light time report
login dark

### CODE REVIEW

**Comment by aiqueneldar** [comment]
It is true that I both know and have tested this PR with @Bluebottel.
@krakan I think these front end changes would improve the usability of this alternative front end greatly!

**Comment by krakan** [comment]
Beautiful! Thank you!

One thing though; 
Here's a screen shot from Firefox on my Oneplus6 phone. Is there a minimum screen size required? Can it be fixed to work on even smaller screens?

**Comment by Bluebottel** [comment]
There is no minimum limit however the top buttons have limited squishiness. The row panels have no limit at all which could explain why they look to squeezed together. They seem to line up with name+week text so I suspect that either flexbox is messed up or it's something with the viewport. I'll have a look at it tonight and see if I can replicate it.

Does it remain the same in chrome? And have you changed any zoom settings? None of those should matter but it's a potential point of failure.

**Comment by krakan** [comment]
Yes, it's the same in Chrome. The screen shot was after zooming a bit back and forth but it was unreadable before zooming too.

I experimented a bit on my laptop and saw that it's when the browser reports a media-width less than 1000px that it changes the layout. Disabling the mobile mode makes it readable also on small screens but then it doesn't quite fit on the screen.

**Comment by Bluebottel** [comment]
I've tried to reproduce the bug without success on my Oneplus 5T which has a similar resolution as yours but I can't seem to trigger it. I've used both Firefox and Chrome and zoomed in and out a bunch as well as rotating the screen. I took a first stab at solving it in the added branch. Try it out and send a screenshot in case it's still messed up.

Note that I've messed with the colors so I can see what's being deformed so it will look a bit messed up.

**Comment by krakan** [comment]
So, the problem I see is that when the resolution goes below 1000px the font-size goes from 12px to 32px and other styles change accordingly which means that it no longer fits on the screen of my android phone. In Firefox on my laptop there's also a "Responsive design" mode (bound to Ctrl-Shift-m) that let's you change the apparent screen resolution. If I just remove the "Mobile mode" block in the common.css file it works better but  not completely.

Shouldn't the font-size and other settings be smaller to fit on a smaller screen?

**Comment by krakan** [comment]
I merged this and will try to fix the small screen issues later.

**Comment by Bluebottel** [comment]
> Shouldn't the font-size and other settings be smaller to fit on a smaller screen?

Contrary to intuition no. Phones have much smaller screens but their resolution is largely the same as a desktop albeit in a different orientation for the most part so it's generally required to have larger pixel sizes for fonts on mobile devices.

From your screenshot it appears that the "Rader" block is squished together when it really shouldn't be. Is that still the case? Changing font sizes is easy enough and tweaking that number so it looks nice shouldn't take too much effort but I'm not sure what's causing the box issue. The bughunt branch contains a commit that makes the entire page look pretty ugly but useful for picking apart what might be wrong.

If you could take a screenshot with a build from that commit I'd appreciate it. I might be able to solve the both the font size and the box not stretching out issue in one swoop.

**Comment by krakan** [comment]
I suspected as much- although it doesn't totally make sense as the condition to detect a small screen is the resolution - ie. `@media (max-width: 1000px) {` - that condition will only be true for devices that indeed have smaller resolution ...

On my master branch I did this:
```
 /* Mobile mode */
-@media (max-width: 1000px) {
+@media (max-width: 500px) {
     html, body {
-   font-size: 32px;
+   font-size: 18px;
    margin: 0.2em;
     }
```
which seems to work for my devices at least.

I'll attach 4 screen shots; 3 from the bughunt 
2020-08-03-201811_1181x887_scrot
2020-08-03-201831_1158x882_scrot
2020-08-03-201957_597x881_scrot
2020-08-03-203237_586x882_scrot



branch with different resolutions (1001px, 1000px and 500px) and the last one from the current master branch at 500px.

**Pull request merged**
